name: build

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PACKER_VERSION: "1.7.0"
      VAGRANT_VERSION: "2.2.14"

    steps:
    - uses: actions/checkout@v2

    - name: Install packer
      run: |
        set -euo pipefail
        set -x

        PACKER_URL="https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
        wget $PACKER_URL
        unzip packer_${PACKER_VERSION}_linux_amd64.zip
        sudo mv packer /usr/local/bin

        packer --version

    - name: Install vagrant
      run: |
        set -euo pipefail
        set -x

        VAGRANT_URL="https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb"
        dir=`mktemp -d tmp-downloaded-vagrant-deb-XXXXX`
        curl -L "${VAGRANT_URL}" > $dir/vagrant.deb;
        sudo apt install $PWD/$dir/vagrant.deb;

    - name: run build
      run: |
        set -x
        sudo modprobe kvm || true
        sudo modprobe kvm_intel || true

        # ??
        # modprobe kvm-intel nested=1

        : "show id"
        id

        : "cpu info"

        egrep '(vmx|svm)' /proc/cpuinfo || true

        : "modules"

        lsmod | grep kvm

        : "rest"

        set -euo pipefail
        set -x

        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          pv \
          qemu-kvm \
          qemu-utils
        make packer-build

    - name: Extract start of changelog
      run: |
        set -euo pipefail
        set -x

        ./topmost-changelog-sec.sh > release-notes.md

    - name: Release (if tagged)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          output/*
          vagrant.d.tgz
        body_path: release-notes.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to vagrant cloud (if tagged)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        set -euo pipefail
        set -x

        ./publish.sh
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

# vim: ts=2 sw=2 et :
